// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortener.Infrastructure;

namespace URLShortener.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("URLShortener.Contracts.Data.Entities.URL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("HitCount")
                        .HasColumnType("bigint");

                    b.Property<string>("LongURLVersion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShortURLVersion")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LongURLVersion")
                        .IsUnique()
                        .HasFilter("[LongURLVersion] IS NOT NULL");

                    b.HasIndex("ShortURLVersion")
                        .IsUnique()
                        .HasFilter("[ShortURLVersion] IS NOT NULL");

                    b.ToTable("URLs");
                });
#pragma warning restore 612, 618
        }
    }
}
